// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:trackora/features/categories/data/models/category_model.dart';
import 'package:trackora/features/transactions/data/models/transaction_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryModelAdapter());
    registerAdapter(CategoryTypeModelAdapter());
    registerAdapter(TransactionModelAdapter());
    registerAdapter(TransactionTypeModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryModelAdapter());
    registerAdapter(CategoryTypeModelAdapter());
    registerAdapter(TransactionModelAdapter());
    registerAdapter(TransactionTypeModelAdapter());
  }
}
